export const coursesInProgress = [
	{
		id: 12,
		title: "Introduction to AI",
		description:
			"Learn the basics of Artificial Intelligence and its applications.",
		provider: "Tech Academy",
		image: "/ai-course.svg",
		price: "$100",
		originalPrice: "$200",
		lectures: 10,
		ratings: "/icons/ratings.svg",
		lastUpdated: "2024-01-01",
		certificateAvailable: true,
		progress: 68,
	},
	{
		id: 13,
		title: "Advanced Machine Learning",
		description:
			"Deep dive into advanced machine learning algorithms and techniques.",
		provider: "Data Science Institute",
		image: "/ai-course.svg",
		price: "$150",
		originalPrice: "$300",
		lectures: 20,
		ratings: "/icons/ratings.svg",
		lastUpdated: "2024-02-01",
		certificateAvailable: true,
		progress: 30,
	},
	{
		id: 14,
		title: "Advanced Machine Learning",
		description:
			"Deep dive into advanced machine learning algorithms and techniques.",
		provider: "Data Science Institute",
		image: "/ai-course.svg",
		price: "$150",
		originalPrice: "$300",
		lectures: 20,
		ratings: "/icons/ratings.svg",
		lastUpdated: "2024-02-01",
		certificateAvailable: true,
		progress: 50,
	},
];
